version: '3.3'

services:
  s_stock_exchange:
    container_name: c_stock_exchange
    image: stock_exchange:0.1
    restart: always
    networks:
      - app-net
    ports:
      - 8081:8080
      
networks:
  app-net:
    name: app-net